; SmartZoo — ESP32-S3 Sense Firmware
; Módulo 1: Setup + Servo Sweep

[env:seeed_xiao_esp32s3]
platform  = espressif32
board     = seeed_xiao_esp32s3
framework = arduino

; Monitor serial
monitor_speed = 115200

; Build flags
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1   ; habilita Serial via USB nativo do ESP32-S3
    -DCORE_DEBUG_LEVEL=0
