; SmartZoo — ESP32-S3 Sense Firmware
; Módulo 4: Person Detection via TFLite Micro

[env:seeed_xiao_esp32s3]
platform  = espressif32
board     = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200

extra_scripts = pre:scripts/setup_tflite.py

lib_deps =
    https://github.com/espressif/esp32-camera.git
    knolleary/PubSubClient @ ^2.8
    https://github.com/tensorflow/tflite-micro-arduino-examples.git

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
    -DTF_LITE_STATIC_MEMORY
    -O2
