; SmartZoo — ESP32-S3 Sense Firmware
; Módulo 2: Detecção de Presença + Localização (Background Subtraction)

[env:seeed_xiao_esp32s3]
platform  = espressif32
board     = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200

lib_deps =
    https://github.com/espressif/esp32-camera.git

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
